name       : kicad-i18n
version    : 5.1.2
release    : 2
source     :
    - https://github.com/KiCad/kicad-i18n/archive/5.1.2.tar.gz : a07ffc5c5cb61b2a81ff7716fbfd8f0d7a470961e7660d5d8e424a91bcf7d6e7
license    : Public Domain
component  : office
summary    : Translations for KiCad
description: |
    po files that is used for the GUI translations for KiCad
setup      : |
    mkdir build && cd build
    %cmake ..
install    : |
    %make_install -C build
