name       : kicad-i18n
version    : 5.1.6
release    : 3
source     :
    - https://gitlab.com/kicad/code/kicad-i18n/-/archive/5.1.6/kicad-i18n-5.1.6.tar.gz : bca4c86391a5e33cd2a41372fceb2803951ab2832b9e09a95161390d42f1f0f5
license    : Public Domain
component  : office.scientific
summary    : Translations for KiCad
description: |
    po files that is used for the GUI translations for KiCad
setup      : |
    mkdir build && cd build
    %cmake ..
install    : |
    %make_install -C build
